// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgChat.proto

package MsgPB;

public final class MsgChat {
  private MsgChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MsgPB.CHANNEL}
   */
  public enum CHANNEL
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WORLD = 1;</code>
     */
    WORLD(0, 1),
    /**
     * <code>ROOM = 2;</code>
     */
    ROOM(1, 2),
    /**
     * <code>FRIEND = 3;</code>
     */
    FRIEND(2, 3),
    ;

    /**
     * <code>WORLD = 1;</code>
     */
    public static final int WORLD_VALUE = 1;
    /**
     * <code>ROOM = 2;</code>
     */
    public static final int ROOM_VALUE = 2;
    /**
     * <code>FRIEND = 3;</code>
     */
    public static final int FRIEND_VALUE = 3;


    public final int getNumber() { return value; }

    public static CHANNEL valueOf(int value) {
      switch (value) {
        case 1: return WORLD;
        case 2: return ROOM;
        case 3: return FRIEND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CHANNEL>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CHANNEL>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CHANNEL>() {
            public CHANNEL findValueByNumber(int number) {
              return CHANNEL.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MsgPB.MsgChat.getDescriptor().getEnumTypes().get(0);
    }

    private static final CHANNEL[] VALUES = values();

    public static CHANNEL valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CHANNEL(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgPB.CHANNEL)
  }

  public interface Msg_Chat_C2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 MsgID = 1 [default = 3];
    /**
     * <code>optional int32 MsgID = 1 [default = 3];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional int32 MsgID = 1 [default = 3];</code>
     */
    int getMsgID();

    // required .MsgPB.CHANNEL channel = 2;
    /**
     * <code>required .MsgPB.CHANNEL channel = 2;</code>
     */
    boolean hasChannel();
    /**
     * <code>required .MsgPB.CHANNEL channel = 2;</code>
     */
    MsgPB.MsgChat.CHANNEL getChannel();

    // optional int32 receiver = 3;
    /**
     * <code>optional int32 receiver = 3;</code>
     */
    boolean hasReceiver();
    /**
     * <code>optional int32 receiver = 3;</code>
     */
    int getReceiver();

    // required string message = 4;
    /**
     * <code>required string message = 4;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 4;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code MsgPB.Msg_Chat_C2S}
   */
  public static final class Msg_Chat_C2S extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Chat_C2SOrBuilder {
    // Use Msg_Chat_C2S.newBuilder() to construct.
    private Msg_Chat_C2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_Chat_C2S(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_Chat_C2S defaultInstance;
    public static Msg_Chat_C2S getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_Chat_C2S getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_Chat_C2S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgID_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              MsgPB.MsgChat.CHANNEL value = MsgPB.MsgChat.CHANNEL.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                channel_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              receiver_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgPB.MsgChat.internal_static_MsgPB_Msg_Chat_C2S_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgPB.MsgChat.internal_static_MsgPB_Msg_Chat_C2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgPB.MsgChat.Msg_Chat_C2S.class, MsgPB.MsgChat.Msg_Chat_C2S.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_Chat_C2S> PARSER =
        new com.google.protobuf.AbstractParser<Msg_Chat_C2S>() {
      public Msg_Chat_C2S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_Chat_C2S(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_Chat_C2S> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 MsgID = 1 [default = 3];
    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgID_;
    /**
     * <code>optional int32 MsgID = 1 [default = 3];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 MsgID = 1 [default = 3];</code>
     */
    public int getMsgID() {
      return msgID_;
    }

    // required .MsgPB.CHANNEL channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private MsgPB.MsgChat.CHANNEL channel_;
    /**
     * <code>required .MsgPB.CHANNEL channel = 2;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MsgPB.CHANNEL channel = 2;</code>
     */
    public MsgPB.MsgChat.CHANNEL getChannel() {
      return channel_;
    }

    // optional int32 receiver = 3;
    public static final int RECEIVER_FIELD_NUMBER = 3;
    private int receiver_;
    /**
     * <code>optional int32 receiver = 3;</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 receiver = 3;</code>
     */
    public int getReceiver() {
      return receiver_;
    }

    // required string message = 4;
    public static final int MESSAGE_FIELD_NUMBER = 4;
    private java.lang.Object message_;
    /**
     * <code>required string message = 4;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = 3;
      channel_ = MsgPB.MsgChat.CHANNEL.WORLD;
      receiver_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, channel_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, receiver_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, channel_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, receiver_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MsgPB.MsgChat.Msg_Chat_C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MsgPB.MsgChat.Msg_Chat_C2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MsgPB.Msg_Chat_C2S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MsgPB.MsgChat.Msg_Chat_C2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgPB.MsgChat.internal_static_MsgPB_Msg_Chat_C2S_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgPB.MsgChat.internal_static_MsgPB_Msg_Chat_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgPB.MsgChat.Msg_Chat_C2S.class, MsgPB.MsgChat.Msg_Chat_C2S.Builder.class);
      }

      // Construct using MsgPB.MsgChat.Msg_Chat_C2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = 3;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = MsgPB.MsgChat.CHANNEL.WORLD;
        bitField0_ = (bitField0_ & ~0x00000002);
        receiver_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgPB.MsgChat.internal_static_MsgPB_Msg_Chat_C2S_descriptor;
      }

      public MsgPB.MsgChat.Msg_Chat_C2S getDefaultInstanceForType() {
        return MsgPB.MsgChat.Msg_Chat_C2S.getDefaultInstance();
      }

      public MsgPB.MsgChat.Msg_Chat_C2S build() {
        MsgPB.MsgChat.Msg_Chat_C2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MsgPB.MsgChat.Msg_Chat_C2S buildPartial() {
        MsgPB.MsgChat.Msg_Chat_C2S result = new MsgPB.MsgChat.Msg_Chat_C2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.receiver_ = receiver_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgPB.MsgChat.Msg_Chat_C2S) {
          return mergeFrom((MsgPB.MsgChat.Msg_Chat_C2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgPB.MsgChat.Msg_Chat_C2S other) {
        if (other == MsgPB.MsgChat.Msg_Chat_C2S.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasReceiver()) {
          setReceiver(other.getReceiver());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000008;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgPB.MsgChat.Msg_Chat_C2S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgPB.MsgChat.Msg_Chat_C2S) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 MsgID = 1 [default = 3];
      private int msgID_ = 3;
      /**
       * <code>optional int32 MsgID = 1 [default = 3];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 MsgID = 1 [default = 3];</code>
       */
      public int getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional int32 MsgID = 1 [default = 3];</code>
       */
      public Builder setMsgID(int value) {
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 MsgID = 1 [default = 3];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = 3;
        onChanged();
        return this;
      }

      // required .MsgPB.CHANNEL channel = 2;
      private MsgPB.MsgChat.CHANNEL channel_ = MsgPB.MsgChat.CHANNEL.WORLD;
      /**
       * <code>required .MsgPB.CHANNEL channel = 2;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MsgPB.CHANNEL channel = 2;</code>
       */
      public MsgPB.MsgChat.CHANNEL getChannel() {
        return channel_;
      }
      /**
       * <code>required .MsgPB.CHANNEL channel = 2;</code>
       */
      public Builder setChannel(MsgPB.MsgChat.CHANNEL value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MsgPB.CHANNEL channel = 2;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = MsgPB.MsgChat.CHANNEL.WORLD;
        onChanged();
        return this;
      }

      // optional int32 receiver = 3;
      private int receiver_ ;
      /**
       * <code>optional int32 receiver = 3;</code>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 receiver = 3;</code>
       */
      public int getReceiver() {
        return receiver_;
      }
      /**
       * <code>optional int32 receiver = 3;</code>
       */
      public Builder setReceiver(int value) {
        bitField0_ |= 0x00000004;
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 receiver = 3;</code>
       */
      public Builder clearReceiver() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receiver_ = 0;
        onChanged();
        return this;
      }

      // required string message = 4;
      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 4;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string message = 4;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 4;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 4;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgPB.Msg_Chat_C2S)
    }

    static {
      defaultInstance = new Msg_Chat_C2S(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MsgPB.Msg_Chat_C2S)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgPB_Msg_Chat_C2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MsgPB_Msg_Chat_C2S_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgChat.proto\022\005MsgPB\"d\n\014Msg_Chat_C2S\022\020" +
      "\n\005MsgID\030\001 \001(\005:\0013\022\037\n\007channel\030\002 \002(\0162\016.MsgP" +
      "B.CHANNEL\022\020\n\010receiver\030\003 \001(\005\022\017\n\007message\030\004" +
      " \002(\t**\n\007CHANNEL\022\t\n\005WORLD\020\001\022\010\n\004ROOM\020\002\022\n\n\006" +
      "FRIEND\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MsgPB_Msg_Chat_C2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MsgPB_Msg_Chat_C2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MsgPB_Msg_Chat_C2S_descriptor,
              new java.lang.String[] { "MsgID", "Channel", "Receiver", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
