//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocols/Msg.proto
namespace protocols.Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_C2S")]
  public partial class Msg_Login_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Login_C2S() {}
    
    private uint _conMethod;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"conMethod", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint conMethod
    {
      get { return _conMethod; }
      set { _conMethod = value; }
    }
    private string _szName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private string _szPassWord;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"szPassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szPassWord
    {
      get { return _szPassWord; }
      set { _szPassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_S2C")]
  public partial class Msg_Login_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Login_S2C() {}
    
    private uint _clientId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint clientId
    {
      get { return _clientId; }
      set { _clientId = value; }
    }
    private bool _conSuccess;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"conSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool conSuccess
    {
      get { return _conSuccess; }
      set { _conSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_WorldChat_C2S")]
  public partial class Msg_WorldChat_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_WorldChat_C2S() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _szText;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"szText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szText
    {
      get { return _szText; }
      set { _szText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_WorldChat_S2C")]
  public partial class Msg_WorldChat_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_WorldChat_S2C() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _szText;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"szText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szText
    {
      get { return _szText; }
      set { _szText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RoomChat_C2R")]
  public partial class Msg_RoomChat_C2R : global::ProtoBuf.IExtensible
  {
    public Msg_RoomChat_C2R() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _roomID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _szText;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"szText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szText
    {
      get { return _szText; }
      set { _szText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RoomChat_R2C")]
  public partial class Msg_RoomChat_R2C : global::ProtoBuf.IExtensible
  {
    public Msg_RoomChat_R2C() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _roomID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _szText;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"szText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szText
    {
      get { return _szText; }
      set { _szText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_PrivateChat_C2C")]
  public partial class Msg_PrivateChat_C2C : global::ProtoBuf.IExtensible
  {
    public Msg_PrivateChat_C2C() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _targetID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"targetID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint targetID
    {
      get { return _targetID; }
      set { _targetID = value; }
    }
    private string _szText;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"szText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szText
    {
      get { return _szText; }
      set { _szText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RoomOperate_C2S")]
  public partial class Msg_RoomOperate_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_RoomOperate_C2S() {}
    
    private uint _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private RoomOperateType _operateType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomOperateType operateType
    {
      get { return _operateType; }
      set { _operateType = value; }
    }
    private uint _roomID = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private uint _roomUserNumber = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomUserNumber", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomUserNumber
    {
      get { return _roomUserNumber; }
      set { _roomUserNumber = value; }
    }
    private GamePattern _roomPattern = GamePattern.Standard;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomPattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(GamePattern.Standard)]
    public GamePattern roomPattern
    {
      get { return _roomPattern; }
      set { _roomPattern = value; }
    }
    private string _Map = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Map
    {
      get { return _Map; }
      set { _Map = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RoomOperate_S2C")]
  public partial class Msg_RoomOperate_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_RoomOperate_S2C() {}
    
    private uint _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private RoomOperateType _operateType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomOperateType operateType
    {
      get { return _operateType; }
      set { _operateType = value; }
    }
    private uint _roomID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private bool _success;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private uint _roomUserNumber = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomUserNumber", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomUserNumber
    {
      get { return _roomUserNumber; }
      set { _roomUserNumber = value; }
    }
    private GamePattern _roomPattern = GamePattern.Standard;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"roomPattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(GamePattern.Standard)]
    public GamePattern roomPattern
    {
      get { return _roomPattern; }
      set { _roomPattern = value; }
    }
    private readonly global::System.Collections.Generic.List<protoaccount> _players = new global::System.Collections.Generic.List<protoaccount>();
    [global::ProtoBuf.ProtoMember(8, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protoaccount> players
    {
      get { return _players; }
    }
  
    private string _Map = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Map
    {
      get { return _Map; }
      set { _Map = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_StartBattle_C2S")]
  public partial class Msg_StartBattle_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_StartBattle_C2S() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _ID2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ID2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID2
    {
      get { return _ID2; }
      set { _ID2 = value; }
    }
    private uint _roomID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private GamePattern _pattern;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GamePattern pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_StartBattle_S2C")]
  public partial class Msg_StartBattle_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_StartBattle_S2C() {}
    
    private string _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private uint _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _ID2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ID2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID2
    {
      get { return _ID2; }
      set { _ID2 = value; }
    }
    private uint _roomID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private GamePattern _pattern;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GamePattern pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private uint _BattleId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"BattleId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint BattleId
    {
      get { return _BattleId; }
      set { _BattleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_OriginHandCards_S2C")]
  public partial class Msg_OriginHandCards_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_OriginHandCards_S2C() {}
    
    private uint _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private readonly global::System.Collections.Generic.List<protocard> _cards = new global::System.Collections.Generic.List<protocard>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocard> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_GameUpdate_C2S")]
  public partial class Msg_GameUpdate_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_GameUpdate_C2S() {}
    
    private uint _BattleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BattleId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint BattleId
    {
      get { return _BattleId; }
      set { _BattleId = value; }
    }
    private uint _Round;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Round", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint Round
    {
      get { return _Round; }
      set { _Round = value; }
    }
    private protocard _useCard;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"useCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocard useCard
    {
      get { return _useCard; }
      set { _useCard = value; }
    }
    private uint _playerID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint playerID
    {
      get { return _playerID; }
      set { _playerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_GameUpdate_S2C")]
  public partial class Msg_GameUpdate_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_GameUpdate_S2C() {}
    
    private uint _BattleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BattleId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint BattleId
    {
      get { return _BattleId; }
      set { _BattleId = value; }
    }
    private uint _player1_hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player1_hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint player1_hp
    {
      get { return _player1_hp; }
      set { _player1_hp = value; }
    }
    private uint _player2_hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player2_hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint player2_hp
    {
      get { return _player2_hp; }
      set { _player2_hp = value; }
    }
    private protocard _player1_usecard;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"player1_usecard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocard player1_usecard
    {
      get { return _player1_usecard; }
      set { _player1_usecard = value; }
    }
    private protocard _player2_usecard;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"player2_usecard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocard player2_usecard
    {
      get { return _player2_usecard; }
      set { _player2_usecard = value; }
    }
    private protocard _player1_gotCard = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"player1_gotCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocard player1_gotCard
    {
      get { return _player1_gotCard; }
      set { _player1_gotCard = value; }
    }
    private protocard _player2_gotCard = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"player2_gotCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocard player2_gotCard
    {
      get { return _player2_gotCard; }
      set { _player2_gotCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Surrender_C2S")]
  public partial class Msg_Surrender_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Surrender_C2S() {}
    
    private uint _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _BattleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"BattleId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint BattleId
    {
      get { return _BattleId; }
      set { _BattleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Gameover_S2C")]
  public partial class Msg_Gameover_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Gameover_S2C() {}
    
    private uint _BattleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BattleId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint BattleId
    {
      get { return _BattleId; }
      set { _BattleId = value; }
    }
    private uint _player1_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player1_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint player1_id
    {
      get { return _player1_id; }
      set { _player1_id = value; }
    }
    private uint _player2_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player2_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint player2_id
    {
      get { return _player2_id; }
      set { _player2_id = value; }
    }
    private bool _player1_victory;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"player1_victory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool player1_victory
    {
      get { return _player1_victory; }
      set { _player1_victory = value; }
    }
    private bool _player2_victory;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"player2_victory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool player2_victory
    {
      get { return _player2_victory; }
      set { _player2_victory = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RoomList_S2C")]
  public partial class Msg_RoomList_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_RoomList_S2C() {}
    
    private readonly global::System.Collections.Generic.List<protoRoom> _rooms = new global::System.Collections.Generic.List<protoRoom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protoRoom> rooms
    {
      get { return _rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_AccountMsg_C2S")]
  public partial class Msg_AccountMsg_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_AccountMsg_C2S() {}
    
    private uint _requestid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requestid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint requestid
    {
      get { return _requestid; }
      set { _requestid = value; }
    }
    private bool _get;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"get", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool get
    {
      get { return _get; }
      set { _get = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_AccountMsg_S2C")]
  public partial class Msg_AccountMsg_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_AccountMsg_S2C() {}
    
    private protoaccount _account = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protoaccount account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"protoaccount")]
  public partial class protoaccount : global::ProtoBuf.IExtensible
  {
    public protoaccount() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _Score = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private uint _BattleNums = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"BattleNums", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint BattleNums
    {
      get { return _BattleNums; }
      set { _BattleNums = value; }
    }
    private uint _StandardBattles = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"StandardBattles", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint StandardBattles
    {
      get { return _StandardBattles; }
      set { _StandardBattles = value; }
    }
    private uint _RankBattles = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"RankBattles", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RankBattles
    {
      get { return _RankBattles; }
      set { _RankBattles = value; }
    }
    private uint _BattleWins = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"BattleWins", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint BattleWins
    {
      get { return _BattleWins; }
      set { _BattleWins = value; }
    }
    private uint _StandardWins = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"StandardWins", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint StandardWins
    {
      get { return _StandardWins; }
      set { _StandardWins = value; }
    }
    private uint _RankWins = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"RankWins", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RankWins
    {
      get { return _RankWins; }
      set { _RankWins = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _HeadImg = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"HeadImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string HeadImg
    {
      get { return _HeadImg; }
      set { _HeadImg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"protocard")]
  public partial class protocard : global::ProtoBuf.IExtensible
  {
    public protocard() {}
    
    private uint _card_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint card_id
    {
      get { return _card_id; }
      set { _card_id = value; }
    }
    private CardAttribute _card_attribute;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_attribute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CardAttribute card_attribute
    {
      get { return _card_attribute; }
      set { _card_attribute = value; }
    }
    private uint _card_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private uint _card_value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"card_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint card_value
    {
      get { return _card_value; }
      set { _card_value = value; }
    }
    private string _card_image = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"card_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_image
    {
      get { return _card_image; }
      set { _card_image = value; }
    }
    private uint _imgID = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"imgID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint imgID
    {
      get { return _imgID; }
      set { _imgID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"protoRoom")]
  public partial class protoRoom : global::ProtoBuf.IExtensible
  {
    public protoRoom() {}
    
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private string _room_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string room_name
    {
      get { return _room_name; }
      set { _room_name = value; }
    }
    private uint _room_users;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"room_users", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint room_users
    {
      get { return _room_users; }
      set { _room_users = value; }
    }
    private GamePattern _roompattern;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roompattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GamePattern roompattern
    {
      get { return _roompattern; }
      set { _roompattern = value; }
    }
    private string _map = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string map
    {
      get { return _map; }
      set { _map = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GamePattern")]
    public enum GamePattern
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Standard", Value=0)]
      Standard = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Rank", Value=1)]
      Rank = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardAttribute")]
    public enum CardAttribute
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"none", Value=0)]
      none = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"fire", Value=1)]
      fire = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"water", Value=2)]
      water = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"wood", Value=3)]
      wood = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"light", Value=4)]
      light = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dark", Value=5)]
      dark = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_C2S", Value=0)]
      LOGIN_C2S = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_S2C", Value=1)]
      LOGIN_S2C = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORLDCHAT_C2S", Value=2)]
      WORLDCHAT_C2S = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORLDCHAT_S2C", Value=3)]
      WORLDCHAT_S2C = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOMCHAT_C2R", Value=4)]
      ROOMCHAT_C2R = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOMCHAT_R2C", Value=5)]
      ROOMCHAT_R2C = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVATECHAT_C2C", Value=6)]
      PRIVATECHAT_C2C = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomOperate_C2S", Value=7)]
      RoomOperate_C2S = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomOperate_S2C", Value=8)]
      RoomOperate_S2C = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartBattle_C2S", Value=9)]
      StartBattle_C2S = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartBattle_S2C", Value=10)]
      StartBattle_S2C = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameUpdate_C2S", Value=11)]
      GameUpdate_C2S = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameUpdate_S2C", Value=12)]
      GameUpdate_S2C = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Surrender_C2S", Value=13)]
      Surrender_C2S = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOver_S2C", Value=14)]
      GameOver_S2C = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OriginHandCards_S2C", Value=15)]
      OriginHandCards_S2C = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomList_S2C", Value=16)]
      RoomList_S2C = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccountMsg_C2S", Value=17)]
      AccountMsg_C2S = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccountMsg_S2C", Value=18)]
      AccountMsg_S2C = 18
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomOperateType")]
    public enum RoomOperateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATEROOM", Value=0)]
      CREATEROOM = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOINROOM", Value=1)]
      JOINROOM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXITROOM", Value=2)]
      EXITROOM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOMMESSAGE", Value=3)]
      ROOMMESSAGE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOMLIST", Value=4)]
      ROOMLIST = 4
    }
  
}