//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocols/Msg.proto
namespace protocols.Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_C2S")]
  public partial class Msg_Login_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Login_C2S() {}
    
    private MsgType _MsgID = MsgType.LOGIN_C2S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgType.LOGIN_C2S)]
    public MsgType MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private int _conMethod;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"conMethod", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int conMethod
    {
      get { return _conMethod; }
      set { _conMethod = value; }
    }
    private string _szName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private string _szPassWord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"szPassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szPassWord
    {
      get { return _szPassWord; }
      set { _szPassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_S2C")]
  public partial class Msg_Login_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Login_S2C() {}
    
    private MsgType _MsgID = MsgType.LOGIN_S2C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgType.LOGIN_S2C)]
    public MsgType MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private long _LoginTimeStamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LoginTimeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long LoginTimeStamp
    {
      get { return _LoginTimeStamp; }
      set { _LoginTimeStamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Connect_S2C")]
  public partial class Msg_Connect_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Connect_S2C() {}
    
    private MsgType _MsgID = MsgType.Connect_S2C;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgType.Connect_S2C)]
    public MsgType MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_C2S", Value=0)]
      LOGIN_C2S = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_S2C", Value=1)]
      LOGIN_S2C = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Connect_S2C", Value=2)]
      Connect_S2C = 2
    }
  
}