//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocols/Msg.proto
namespace protocols.Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_C2S")]
  public partial class Msg_Login_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Login_C2S() {}
    
    private MsgType _MsgID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MsgType MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private uint _conMethod;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"conMethod", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint conMethod
    {
      get { return _conMethod; }
      set { _conMethod = value; }
    }
    private string _szName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private string _szPassWord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"szPassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szPassWord
    {
      get { return _szPassWord; }
      set { _szPassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_S2C")]
  public partial class Msg_Login_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Login_S2C() {}
    
    private MsgType _MsgID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MsgType MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private uint _clientId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"clientId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint clientId
    {
      get { return _clientId; }
      set { _clientId = value; }
    }
    private bool _conSuccess;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"conSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool conSuccess
    {
      get { return _conSuccess; }
      set { _conSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GamePattern")]
    public enum GamePattern
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Standard", Value=0)]
      Standard = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Rank", Value=1)]
      Rank = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardAttribute")]
    public enum CardAttribute
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"none", Value=0)]
      none = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"fire", Value=1)]
      fire = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"water", Value=2)]
      water = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"wood", Value=3)]
      wood = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"light", Value=4)]
      light = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dark", Value=5)]
      dark = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_C2S", Value=0)]
      LOGIN_C2S = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_S2C", Value=1)]
      LOGIN_S2C = 1
    }
  
}