//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2021/2/4 20:30:04]
#pragma once
# include "tabletool/myconfig.h"
# include "tabletool/singleton.h"
# include "tabletool/readtablefield.h"
# include "tablestruct.h"


bool LoadTableConfig();


struct tbsChessTypeItem {
  int id;
  int type;
  int attack;
};

class cfgChessTypeTable:public IConfigTable<tbsChessTypeItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "ChessType.txt";
        return f;
    }

};


struct tbsGlobalCfgItem {
  int id;
  string ServerIP;
  int ServerPort;
};

class cfgGlobalCfgTable:public IConfigTable<tbsGlobalCfgItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "GlobalCfg.txt";
        return f;
    }

};

