//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2021/3/8 22:45:45]
#pragma once
# include "tabletool/myconfig.h"
# include "tabletool/singleton.h"
# include "tabletool/readtablefield.h"
# include "tablestruct.h"


bool LoadTableConfig();


struct tbsChessTypeItem {
  int id;
  int type;
  string strName;
  string strEng;
};

class cfgChessTypeTable:public IConfigTable<tbsChessTypeItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "ChessType.txt";
        return f;
    }

};


struct tbsDatabaseCfgItem {
  int id;
  string host;
  string user;
  string password;
  string database;
  int port;
  int unix_socket;
  int clientflag;
};

class cfgDatabaseCfgTable:public IConfigTable<tbsDatabaseCfgItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "DatabaseCfg.txt";
        return f;
    }

};


struct tbsGlobalCfgItem {
  int id;
  string ServerIP;
  int ServerPort;
};

class cfgGlobalCfgTable:public IConfigTable<tbsGlobalCfgItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "GlobalCfg.txt";
        return f;
    }

};

