//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2021/2/4 20:30:04]
#include "tableconfig.h"

bool LoadTableConfig()
{
    stConfigScope scope;
    if(false == Singleton<cfgChessTypeTable>::Instance()->Load())
    {
        ErrorLog("加载配置%s出错",Singleton<cfgChessTypeTable>::Instance()->GetTableFile().c_str() );
        return false;
    }
    if(false == Singleton<cfgGlobalCfgTable>::Instance()->Load())
    {
        ErrorLog("加载配置%s出错",Singleton<cfgGlobalCfgTable>::Instance()->GetTableFile().c_str() );
        return false;
    }
    return true;
}

bool cfgChessTypeTable::Load()
{
	ReadTableFile reader;
	reader.Initialize();

	if (!reader.Init(GetTableFile().c_str()))
		return false;

	DataReader dr;
	int iRows = reader.GetRowCount();
	int iCols = reader.GetColCount();

	for (int i = 1; i < iRows; ++i)
	{
		tbsChessTypeItem item;
		item.id = atoi(reader.GetValue(i, "id"));
		item.type = atoi(reader.GetValue(i, "type"));
		item.attack = atoi(reader.GetValue(i, "attack"));
		m_Items[item.id] = item;
	}

	return true;
}
bool cfgGlobalCfgTable::Load()
{
	ReadTableFile reader;
	reader.Initialize();

	if (!reader.Init(GetTableFile().c_str()))
		return false;

	DataReader dr;
	int iRows = reader.GetRowCount();
	int iCols = reader.GetColCount();

	for (int i = 1; i < iRows; ++i)
	{
		tbsGlobalCfgItem item;
		item.id = atoi(reader.GetValue(i, "id"));
		item.ServerIP = (reader.GetValue(i, "ServerIP"));
		item.ServerPort = atoi(reader.GetValue(i, "ServerPort"));
		m_Items[item.id] = item;
	}

	return true;
}
