// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code GamePattern}
   *
   * <pre>
   *游戏模式
   * </pre>
   */
  public enum GamePattern
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Standard = 0;</code>
     */
    Standard(0, 0),
    /**
     * <code>Rank = 1;</code>
     */
    Rank(1, 1),
    ;

    /**
     * <code>Standard = 0;</code>
     */
    public static final int Standard_VALUE = 0;
    /**
     * <code>Rank = 1;</code>
     */
    public static final int Rank_VALUE = 1;


    public final int getNumber() { return value; }

    public static GamePattern valueOf(int value) {
      switch (value) {
        case 0: return Standard;
        case 1: return Rank;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GamePattern>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GamePattern>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GamePattern>() {
            public GamePattern findValueByNumber(int number) {
              return GamePattern.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Msg.getDescriptor().getEnumTypes().get(0);
    }

    private static final GamePattern[] VALUES = values();

    public static GamePattern valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GamePattern(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GamePattern)
  }

  /**
   * Protobuf enum {@code CardAttribute}
   *
   * <pre>
   *卡牌属性
   * </pre>
   */
  public enum CardAttribute
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>none = 0;</code>
     */
    none(0, 0),
    /**
     * <code>fire = 1;</code>
     */
    fire(1, 1),
    /**
     * <code>water = 2;</code>
     */
    water(2, 2),
    /**
     * <code>wood = 3;</code>
     */
    wood(3, 3),
    /**
     * <code>light = 4;</code>
     */
    light(4, 4),
    /**
     * <code>dark = 5;</code>
     */
    dark(5, 5),
    ;

    /**
     * <code>none = 0;</code>
     */
    public static final int none_VALUE = 0;
    /**
     * <code>fire = 1;</code>
     */
    public static final int fire_VALUE = 1;
    /**
     * <code>water = 2;</code>
     */
    public static final int water_VALUE = 2;
    /**
     * <code>wood = 3;</code>
     */
    public static final int wood_VALUE = 3;
    /**
     * <code>light = 4;</code>
     */
    public static final int light_VALUE = 4;
    /**
     * <code>dark = 5;</code>
     */
    public static final int dark_VALUE = 5;


    public final int getNumber() { return value; }

    public static CardAttribute valueOf(int value) {
      switch (value) {
        case 0: return none;
        case 1: return fire;
        case 2: return water;
        case 3: return wood;
        case 4: return light;
        case 5: return dark;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CardAttribute>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CardAttribute>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CardAttribute>() {
            public CardAttribute findValueByNumber(int number) {
              return CardAttribute.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Msg.getDescriptor().getEnumTypes().get(1);
    }

    private static final CardAttribute[] VALUES = values();

    public static CardAttribute valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CardAttribute(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CardAttribute)
  }

  /**
   * Protobuf enum {@code MsgType}
   *
   * <pre>
   *消息类型
   * </pre>
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_C2S = 0;</code>
     *
     * <pre>
     *登录
     * </pre>
     */
    LOGIN_C2S(0, 0),
    /**
     * <code>LOGIN_S2C = 1;</code>
     */
    LOGIN_S2C(1, 1),
    ;

    /**
     * <code>LOGIN_C2S = 0;</code>
     *
     * <pre>
     *登录
     * </pre>
     */
    public static final int LOGIN_C2S_VALUE = 0;
    /**
     * <code>LOGIN_S2C = 1;</code>
     */
    public static final int LOGIN_S2C_VALUE = 1;


    public final int getNumber() { return value; }

    public static MsgType valueOf(int value) {
      switch (value) {
        case 0: return LOGIN_C2S;
        case 1: return LOGIN_S2C;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Msg.getDescriptor().getEnumTypes().get(2);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgType)
  }

  public interface Msg_Login_C2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .MsgType MsgID = 1 [default = LOGIN_C2S];
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    boolean hasMsgID();
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    Msg.MsgType getMsgID();

    // required fixed32 conMethod = 2;
    /**
     * <code>required fixed32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    boolean hasConMethod();
    /**
     * <code>required fixed32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    int getConMethod();

    // required string szName = 3;
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    boolean hasSzName();
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    java.lang.String getSzName();
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    com.google.protobuf.ByteString
        getSzNameBytes();

    // required string szPassWord = 4;
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    boolean hasSzPassWord();
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    java.lang.String getSzPassWord();
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getSzPassWordBytes();
  }
  /**
   * Protobuf type {@code Msg_Login_C2S}
   *
   * <pre>
   *登录消息
   * </pre>
   */
  public static final class Msg_Login_C2S extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Login_C2SOrBuilder {
    // Use Msg_Login_C2S.newBuilder() to construct.
    private Msg_Login_C2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_Login_C2S(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_Login_C2S defaultInstance;
    public static Msg_Login_C2S getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_Login_C2S getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_Login_C2S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Msg.MsgType value = Msg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              conMethod_ = input.readFixed32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              szName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              szPassWord_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_Msg_Login_C2S_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_Msg_Login_C2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.Msg_Login_C2S.class, Msg.Msg_Login_C2S.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_Login_C2S> PARSER =
        new com.google.protobuf.AbstractParser<Msg_Login_C2S>() {
      public Msg_Login_C2S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_Login_C2S(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_Login_C2S> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .MsgType MsgID = 1 [default = LOGIN_C2S];
    public static final int MSGID_FIELD_NUMBER = 1;
    private Msg.MsgType msgID_;
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    public Msg.MsgType getMsgID() {
      return msgID_;
    }

    // required fixed32 conMethod = 2;
    public static final int CONMETHOD_FIELD_NUMBER = 2;
    private int conMethod_;
    /**
     * <code>required fixed32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    public boolean hasConMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    public int getConMethod() {
      return conMethod_;
    }

    // required string szName = 3;
    public static final int SZNAME_FIELD_NUMBER = 3;
    private java.lang.Object szName_;
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    public boolean hasSzName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    public java.lang.String getSzName() {
      java.lang.Object ref = szName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          szName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSzNameBytes() {
      java.lang.Object ref = szName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        szName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string szPassWord = 4;
    public static final int SZPASSWORD_FIELD_NUMBER = 4;
    private java.lang.Object szPassWord_;
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public boolean hasSzPassWord() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public java.lang.String getSzPassWord() {
      java.lang.Object ref = szPassWord_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          szPassWord_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSzPassWordBytes() {
      java.lang.Object ref = szPassWord_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        szPassWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = Msg.MsgType.LOGIN_C2S;
      conMethod_ = 0;
      szName_ = "";
      szPassWord_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSzName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSzPassWord()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, conMethod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSzNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSzPassWordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, conMethod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSzNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSzPassWordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.Msg_Login_C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.Msg_Login_C2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg_Login_C2S}
     *
     * <pre>
     *登录消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.Msg_Login_C2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_Msg_Login_C2S_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_Msg_Login_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.Msg_Login_C2S.class, Msg.Msg_Login_C2S.Builder.class);
      }

      // Construct using Msg.Msg_Login_C2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = Msg.MsgType.LOGIN_C2S;
        bitField0_ = (bitField0_ & ~0x00000001);
        conMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        szName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        szPassWord_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_Msg_Login_C2S_descriptor;
      }

      public Msg.Msg_Login_C2S getDefaultInstanceForType() {
        return Msg.Msg_Login_C2S.getDefaultInstance();
      }

      public Msg.Msg_Login_C2S build() {
        Msg.Msg_Login_C2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.Msg_Login_C2S buildPartial() {
        Msg.Msg_Login_C2S result = new Msg.Msg_Login_C2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.conMethod_ = conMethod_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.szName_ = szName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.szPassWord_ = szPassWord_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.Msg_Login_C2S) {
          return mergeFrom((Msg.Msg_Login_C2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.Msg_Login_C2S other) {
        if (other == Msg.Msg_Login_C2S.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasConMethod()) {
          setConMethod(other.getConMethod());
        }
        if (other.hasSzName()) {
          bitField0_ |= 0x00000004;
          szName_ = other.szName_;
          onChanged();
        }
        if (other.hasSzPassWord()) {
          bitField0_ |= 0x00000008;
          szPassWord_ = other.szPassWord_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgID()) {
          
          return false;
        }
        if (!hasConMethod()) {
          
          return false;
        }
        if (!hasSzName()) {
          
          return false;
        }
        if (!hasSzPassWord()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.Msg_Login_C2S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.Msg_Login_C2S) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .MsgType MsgID = 1 [default = LOGIN_C2S];
      private Msg.MsgType msgID_ = Msg.MsgType.LOGIN_C2S;
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Msg.MsgType getMsgID() {
        return msgID_;
      }
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Builder setMsgID(Msg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = Msg.MsgType.LOGIN_C2S;
        onChanged();
        return this;
      }

      // required fixed32 conMethod = 2;
      private int conMethod_ ;
      /**
       * <code>required fixed32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public boolean hasConMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public int getConMethod() {
        return conMethod_;
      }
      /**
       * <code>required fixed32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public Builder setConMethod(int value) {
        bitField0_ |= 0x00000002;
        conMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public Builder clearConMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        conMethod_ = 0;
        onChanged();
        return this;
      }

      // required string szName = 3;
      private java.lang.Object szName_ = "";
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public boolean hasSzName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public java.lang.String getSzName() {
        java.lang.Object ref = szName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          szName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSzNameBytes() {
        java.lang.Object ref = szName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          szName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public Builder setSzName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        szName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public Builder clearSzName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        szName_ = getDefaultInstance().getSzName();
        onChanged();
        return this;
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public Builder setSzNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        szName_ = value;
        onChanged();
        return this;
      }

      // required string szPassWord = 4;
      private java.lang.Object szPassWord_ = "";
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public boolean hasSzPassWord() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public java.lang.String getSzPassWord() {
        java.lang.Object ref = szPassWord_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          szPassWord_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSzPassWordBytes() {
        java.lang.Object ref = szPassWord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          szPassWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setSzPassWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        szPassWord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder clearSzPassWord() {
        bitField0_ = (bitField0_ & ~0x00000008);
        szPassWord_ = getDefaultInstance().getSzPassWord();
        onChanged();
        return this;
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setSzPassWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        szPassWord_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg_Login_C2S)
    }

    static {
      defaultInstance = new Msg_Login_C2S(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg_Login_C2S)
  }

  public interface Msg_Login_S2COrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .MsgType MsgID = 1 [default = LOGIN_C2S];
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    boolean hasMsgID();
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    Msg.MsgType getMsgID();

    // required fixed32 clientId = 2;
    /**
     * <code>required fixed32 clientId = 2;</code>
     *
     * <pre>
     *服务器端内部维护的客户ID
     * </pre>
     */
    boolean hasClientId();
    /**
     * <code>required fixed32 clientId = 2;</code>
     *
     * <pre>
     *服务器端内部维护的客户ID
     * </pre>
     */
    int getClientId();

    // required bool conSuccess = 3;
    /**
     * <code>required bool conSuccess = 3;</code>
     *
     * <pre>
     *是否连接服务器成功
     * </pre>
     */
    boolean hasConSuccess();
    /**
     * <code>required bool conSuccess = 3;</code>
     *
     * <pre>
     *是否连接服务器成功
     * </pre>
     */
    boolean getConSuccess();
  }
  /**
   * Protobuf type {@code Msg_Login_S2C}
   */
  public static final class Msg_Login_S2C extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Login_S2COrBuilder {
    // Use Msg_Login_S2C.newBuilder() to construct.
    private Msg_Login_S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_Login_S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_Login_S2C defaultInstance;
    public static Msg_Login_S2C getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_Login_S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_Login_S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Msg.MsgType value = Msg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readFixed32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              conSuccess_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_Msg_Login_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_Msg_Login_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.Msg_Login_S2C.class, Msg.Msg_Login_S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_Login_S2C> PARSER =
        new com.google.protobuf.AbstractParser<Msg_Login_S2C>() {
      public Msg_Login_S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_Login_S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_Login_S2C> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .MsgType MsgID = 1 [default = LOGIN_C2S];
    public static final int MSGID_FIELD_NUMBER = 1;
    private Msg.MsgType msgID_;
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    public Msg.MsgType getMsgID() {
      return msgID_;
    }

    // required fixed32 clientId = 2;
    public static final int CLIENTID_FIELD_NUMBER = 2;
    private int clientId_;
    /**
     * <code>required fixed32 clientId = 2;</code>
     *
     * <pre>
     *服务器端内部维护的客户ID
     * </pre>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed32 clientId = 2;</code>
     *
     * <pre>
     *服务器端内部维护的客户ID
     * </pre>
     */
    public int getClientId() {
      return clientId_;
    }

    // required bool conSuccess = 3;
    public static final int CONSUCCESS_FIELD_NUMBER = 3;
    private boolean conSuccess_;
    /**
     * <code>required bool conSuccess = 3;</code>
     *
     * <pre>
     *是否连接服务器成功
     * </pre>
     */
    public boolean hasConSuccess() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool conSuccess = 3;</code>
     *
     * <pre>
     *是否连接服务器成功
     * </pre>
     */
    public boolean getConSuccess() {
      return conSuccess_;
    }

    private void initFields() {
      msgID_ = Msg.MsgType.LOGIN_C2S;
      clientId_ = 0;
      conSuccess_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, conSuccess_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, conSuccess_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.Msg_Login_S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.Msg_Login_S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg_Login_S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.Msg_Login_S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_Msg_Login_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_Msg_Login_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.Msg_Login_S2C.class, Msg.Msg_Login_S2C.Builder.class);
      }

      // Construct using Msg.Msg_Login_S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = Msg.MsgType.LOGIN_C2S;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        conSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_Msg_Login_S2C_descriptor;
      }

      public Msg.Msg_Login_S2C getDefaultInstanceForType() {
        return Msg.Msg_Login_S2C.getDefaultInstance();
      }

      public Msg.Msg_Login_S2C build() {
        Msg.Msg_Login_S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.Msg_Login_S2C buildPartial() {
        Msg.Msg_Login_S2C result = new Msg.Msg_Login_S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.conSuccess_ = conSuccess_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.Msg_Login_S2C) {
          return mergeFrom((Msg.Msg_Login_S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.Msg_Login_S2C other) {
        if (other == Msg.Msg_Login_S2C.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasConSuccess()) {
          setConSuccess(other.getConSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgID()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        if (!hasConSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.Msg_Login_S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.Msg_Login_S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .MsgType MsgID = 1 [default = LOGIN_C2S];
      private Msg.MsgType msgID_ = Msg.MsgType.LOGIN_C2S;
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Msg.MsgType getMsgID() {
        return msgID_;
      }
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Builder setMsgID(Msg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = Msg.MsgType.LOGIN_C2S;
        onChanged();
        return this;
      }

      // required fixed32 clientId = 2;
      private int clientId_ ;
      /**
       * <code>required fixed32 clientId = 2;</code>
       *
       * <pre>
       *服务器端内部维护的客户ID
       * </pre>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed32 clientId = 2;</code>
       *
       * <pre>
       *服务器端内部维护的客户ID
       * </pre>
       */
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>required fixed32 clientId = 2;</code>
       *
       * <pre>
       *服务器端内部维护的客户ID
       * </pre>
       */
      public Builder setClientId(int value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 clientId = 2;</code>
       *
       * <pre>
       *服务器端内部维护的客户ID
       * </pre>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0;
        onChanged();
        return this;
      }

      // required bool conSuccess = 3;
      private boolean conSuccess_ ;
      /**
       * <code>required bool conSuccess = 3;</code>
       *
       * <pre>
       *是否连接服务器成功
       * </pre>
       */
      public boolean hasConSuccess() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool conSuccess = 3;</code>
       *
       * <pre>
       *是否连接服务器成功
       * </pre>
       */
      public boolean getConSuccess() {
        return conSuccess_;
      }
      /**
       * <code>required bool conSuccess = 3;</code>
       *
       * <pre>
       *是否连接服务器成功
       * </pre>
       */
      public Builder setConSuccess(boolean value) {
        bitField0_ |= 0x00000004;
        conSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool conSuccess = 3;</code>
       *
       * <pre>
       *是否连接服务器成功
       * </pre>
       */
      public Builder clearConSuccess() {
        bitField0_ = (bitField0_ & ~0x00000004);
        conSuccess_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg_Login_S2C)
    }

    static {
      defaultInstance = new Msg_Login_S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg_Login_S2C)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Login_C2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Login_C2S_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Login_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Login_S2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\"j\n\rMsg_Login_C2S\022\"\n\005MsgID\030\001 " +
      "\002(\0162\010.MsgType:\tLOGIN_C2S\022\021\n\tconMethod\030\002 " +
      "\002(\007\022\016\n\006szName\030\003 \002(\t\022\022\n\nszPassWord\030\004 \002(\t\"" +
      "Y\n\rMsg_Login_S2C\022\"\n\005MsgID\030\001 \002(\0162\010.MsgTyp" +
      "e:\tLOGIN_C2S\022\020\n\010clientId\030\002 \002(\007\022\022\n\nconSuc" +
      "cess\030\003 \002(\010*%\n\013GamePattern\022\014\n\010Standard\020\000\022" +
      "\010\n\004Rank\020\001*M\n\rCardAttribute\022\010\n\004none\020\000\022\010\n\004" +
      "fire\020\001\022\t\n\005water\020\002\022\010\n\004wood\020\003\022\t\n\005light\020\004\022\010" +
      "\n\004dark\020\005*\'\n\007MsgType\022\r\n\tLOGIN_C2S\020\000\022\r\n\tLO" +
      "GIN_S2C\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Msg_Login_C2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Msg_Login_C2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Login_C2S_descriptor,
              new java.lang.String[] { "MsgID", "ConMethod", "SzName", "SzPassWord", });
          internal_static_Msg_Login_S2C_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Msg_Login_S2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Login_S2C_descriptor,
              new java.lang.String[] { "MsgID", "ClientId", "ConSuccess", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
