// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MsgType}
   *
   * <pre>
   *消息类型
   * </pre>
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_C2S = 0;</code>
     */
    LOGIN_C2S(0, 0),
    /**
     * <code>LOGIN_S2C = 1;</code>
     */
    LOGIN_S2C(1, 1),
    /**
     * <code>Connect_S2C = 2;</code>
     */
    Connect_S2C(2, 2),
    /**
     * <code>Chat_C2S = 3;</code>
     */
    Chat_C2S(3, 3),
    ;

    /**
     * <code>LOGIN_C2S = 0;</code>
     */
    public static final int LOGIN_C2S_VALUE = 0;
    /**
     * <code>LOGIN_S2C = 1;</code>
     */
    public static final int LOGIN_S2C_VALUE = 1;
    /**
     * <code>Connect_S2C = 2;</code>
     */
    public static final int Connect_S2C_VALUE = 2;
    /**
     * <code>Chat_C2S = 3;</code>
     */
    public static final int Chat_C2S_VALUE = 3;


    public final int getNumber() { return value; }

    public static MsgType valueOf(int value) {
      switch (value) {
        case 0: return LOGIN_C2S;
        case 1: return LOGIN_S2C;
        case 2: return Connect_S2C;
        case 3: return Chat_C2S;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Msg.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgType)
  }

  public interface Msg_Login_C2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MsgType MsgID = 1 [default = LOGIN_C2S];
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    Msg.MsgType getMsgID();

    // required int32 conMethod = 2;
    /**
     * <code>required int32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    boolean hasConMethod();
    /**
     * <code>required int32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    int getConMethod();

    // required string szName = 3;
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    boolean hasSzName();
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    java.lang.String getSzName();
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    com.google.protobuf.ByteString
        getSzNameBytes();

    // required string szPassWord = 4;
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    boolean hasSzPassWord();
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    java.lang.String getSzPassWord();
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getSzPassWordBytes();
  }
  /**
   * Protobuf type {@code Msg_Login_C2S}
   *
   * <pre>
   *登录消息
   * </pre>
   */
  public static final class Msg_Login_C2S extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Login_C2SOrBuilder {
    // Use Msg_Login_C2S.newBuilder() to construct.
    private Msg_Login_C2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_Login_C2S(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_Login_C2S defaultInstance;
    public static Msg_Login_C2S getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_Login_C2S getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_Login_C2S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Msg.MsgType value = Msg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              conMethod_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              szName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              szPassWord_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_Msg_Login_C2S_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_Msg_Login_C2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.Msg_Login_C2S.class, Msg.Msg_Login_C2S.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_Login_C2S> PARSER =
        new com.google.protobuf.AbstractParser<Msg_Login_C2S>() {
      public Msg_Login_C2S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_Login_C2S(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_Login_C2S> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MsgType MsgID = 1 [default = LOGIN_C2S];
    public static final int MSGID_FIELD_NUMBER = 1;
    private Msg.MsgType msgID_;
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
     */
    public Msg.MsgType getMsgID() {
      return msgID_;
    }

    // required int32 conMethod = 2;
    public static final int CONMETHOD_FIELD_NUMBER = 2;
    private int conMethod_;
    /**
     * <code>required int32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    public boolean hasConMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 conMethod = 2;</code>
     *
     * <pre>
     *注册还是登录
     * </pre>
     */
    public int getConMethod() {
      return conMethod_;
    }

    // required string szName = 3;
    public static final int SZNAME_FIELD_NUMBER = 3;
    private java.lang.Object szName_;
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    public boolean hasSzName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    public java.lang.String getSzName() {
      java.lang.Object ref = szName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          szName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string szName = 3;</code>
     *
     * <pre>
     *账户名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSzNameBytes() {
      java.lang.Object ref = szName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        szName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string szPassWord = 4;
    public static final int SZPASSWORD_FIELD_NUMBER = 4;
    private java.lang.Object szPassWord_;
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public boolean hasSzPassWord() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public java.lang.String getSzPassWord() {
      java.lang.Object ref = szPassWord_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          szPassWord_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string szPassWord = 4;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSzPassWordBytes() {
      java.lang.Object ref = szPassWord_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        szPassWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = Msg.MsgType.LOGIN_C2S;
      conMethod_ = 0;
      szName_ = "";
      szPassWord_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasConMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSzName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSzPassWord()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, conMethod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSzNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSzPassWordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, conMethod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSzNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSzPassWordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.Msg_Login_C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.Msg_Login_C2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg_Login_C2S}
     *
     * <pre>
     *登录消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.Msg_Login_C2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_Msg_Login_C2S_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_Msg_Login_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.Msg_Login_C2S.class, Msg.Msg_Login_C2S.Builder.class);
      }

      // Construct using Msg.Msg_Login_C2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = Msg.MsgType.LOGIN_C2S;
        bitField0_ = (bitField0_ & ~0x00000001);
        conMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        szName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        szPassWord_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_Msg_Login_C2S_descriptor;
      }

      public Msg.Msg_Login_C2S getDefaultInstanceForType() {
        return Msg.Msg_Login_C2S.getDefaultInstance();
      }

      public Msg.Msg_Login_C2S build() {
        Msg.Msg_Login_C2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.Msg_Login_C2S buildPartial() {
        Msg.Msg_Login_C2S result = new Msg.Msg_Login_C2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.conMethod_ = conMethod_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.szName_ = szName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.szPassWord_ = szPassWord_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.Msg_Login_C2S) {
          return mergeFrom((Msg.Msg_Login_C2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.Msg_Login_C2S other) {
        if (other == Msg.Msg_Login_C2S.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasConMethod()) {
          setConMethod(other.getConMethod());
        }
        if (other.hasSzName()) {
          bitField0_ |= 0x00000004;
          szName_ = other.szName_;
          onChanged();
        }
        if (other.hasSzPassWord()) {
          bitField0_ |= 0x00000008;
          szPassWord_ = other.szPassWord_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasConMethod()) {
          
          return false;
        }
        if (!hasSzName()) {
          
          return false;
        }
        if (!hasSzPassWord()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.Msg_Login_C2S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.Msg_Login_C2S) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MsgType MsgID = 1 [default = LOGIN_C2S];
      private Msg.MsgType msgID_ = Msg.MsgType.LOGIN_C2S;
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Msg.MsgType getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Builder setMsgID(Msg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_C2S];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = Msg.MsgType.LOGIN_C2S;
        onChanged();
        return this;
      }

      // required int32 conMethod = 2;
      private int conMethod_ ;
      /**
       * <code>required int32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public boolean hasConMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public int getConMethod() {
        return conMethod_;
      }
      /**
       * <code>required int32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public Builder setConMethod(int value) {
        bitField0_ |= 0x00000002;
        conMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 conMethod = 2;</code>
       *
       * <pre>
       *注册还是登录
       * </pre>
       */
      public Builder clearConMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        conMethod_ = 0;
        onChanged();
        return this;
      }

      // required string szName = 3;
      private java.lang.Object szName_ = "";
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public boolean hasSzName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public java.lang.String getSzName() {
        java.lang.Object ref = szName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          szName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSzNameBytes() {
        java.lang.Object ref = szName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          szName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public Builder setSzName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        szName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public Builder clearSzName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        szName_ = getDefaultInstance().getSzName();
        onChanged();
        return this;
      }
      /**
       * <code>required string szName = 3;</code>
       *
       * <pre>
       *账户名
       * </pre>
       */
      public Builder setSzNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        szName_ = value;
        onChanged();
        return this;
      }

      // required string szPassWord = 4;
      private java.lang.Object szPassWord_ = "";
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public boolean hasSzPassWord() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public java.lang.String getSzPassWord() {
        java.lang.Object ref = szPassWord_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          szPassWord_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSzPassWordBytes() {
        java.lang.Object ref = szPassWord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          szPassWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setSzPassWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        szPassWord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder clearSzPassWord() {
        bitField0_ = (bitField0_ & ~0x00000008);
        szPassWord_ = getDefaultInstance().getSzPassWord();
        onChanged();
        return this;
      }
      /**
       * <code>required string szPassWord = 4;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setSzPassWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        szPassWord_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg_Login_C2S)
    }

    static {
      defaultInstance = new Msg_Login_C2S(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg_Login_C2S)
  }

  public interface Msg_Login_S2COrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MsgType MsgID = 1 [default = LOGIN_S2C];
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
     */
    Msg.MsgType getMsgID();

    // required int64 LoginTimeStamp = 2;
    /**
     * <code>required int64 LoginTimeStamp = 2;</code>
     */
    boolean hasLoginTimeStamp();
    /**
     * <code>required int64 LoginTimeStamp = 2;</code>
     */
    long getLoginTimeStamp();
  }
  /**
   * Protobuf type {@code Msg_Login_S2C}
   */
  public static final class Msg_Login_S2C extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Login_S2COrBuilder {
    // Use Msg_Login_S2C.newBuilder() to construct.
    private Msg_Login_S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_Login_S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_Login_S2C defaultInstance;
    public static Msg_Login_S2C getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_Login_S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_Login_S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Msg.MsgType value = Msg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              loginTimeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_Msg_Login_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_Msg_Login_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.Msg_Login_S2C.class, Msg.Msg_Login_S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_Login_S2C> PARSER =
        new com.google.protobuf.AbstractParser<Msg_Login_S2C>() {
      public Msg_Login_S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_Login_S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_Login_S2C> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MsgType MsgID = 1 [default = LOGIN_S2C];
    public static final int MSGID_FIELD_NUMBER = 1;
    private Msg.MsgType msgID_;
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
     */
    public Msg.MsgType getMsgID() {
      return msgID_;
    }

    // required int64 LoginTimeStamp = 2;
    public static final int LOGINTIMESTAMP_FIELD_NUMBER = 2;
    private long loginTimeStamp_;
    /**
     * <code>required int64 LoginTimeStamp = 2;</code>
     */
    public boolean hasLoginTimeStamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 LoginTimeStamp = 2;</code>
     */
    public long getLoginTimeStamp() {
      return loginTimeStamp_;
    }

    private void initFields() {
      msgID_ = Msg.MsgType.LOGIN_S2C;
      loginTimeStamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLoginTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, loginTimeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, loginTimeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.Msg_Login_S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Login_S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.Msg_Login_S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg_Login_S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.Msg_Login_S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_Msg_Login_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_Msg_Login_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.Msg_Login_S2C.class, Msg.Msg_Login_S2C.Builder.class);
      }

      // Construct using Msg.Msg_Login_S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = Msg.MsgType.LOGIN_S2C;
        bitField0_ = (bitField0_ & ~0x00000001);
        loginTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_Msg_Login_S2C_descriptor;
      }

      public Msg.Msg_Login_S2C getDefaultInstanceForType() {
        return Msg.Msg_Login_S2C.getDefaultInstance();
      }

      public Msg.Msg_Login_S2C build() {
        Msg.Msg_Login_S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.Msg_Login_S2C buildPartial() {
        Msg.Msg_Login_S2C result = new Msg.Msg_Login_S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginTimeStamp_ = loginTimeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.Msg_Login_S2C) {
          return mergeFrom((Msg.Msg_Login_S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.Msg_Login_S2C other) {
        if (other == Msg.Msg_Login_S2C.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasLoginTimeStamp()) {
          setLoginTimeStamp(other.getLoginTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoginTimeStamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.Msg_Login_S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.Msg_Login_S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MsgType MsgID = 1 [default = LOGIN_S2C];
      private Msg.MsgType msgID_ = Msg.MsgType.LOGIN_S2C;
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
       */
      public Msg.MsgType getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
       */
      public Builder setMsgID(Msg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = LOGIN_S2C];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = Msg.MsgType.LOGIN_S2C;
        onChanged();
        return this;
      }

      // required int64 LoginTimeStamp = 2;
      private long loginTimeStamp_ ;
      /**
       * <code>required int64 LoginTimeStamp = 2;</code>
       */
      public boolean hasLoginTimeStamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 LoginTimeStamp = 2;</code>
       */
      public long getLoginTimeStamp() {
        return loginTimeStamp_;
      }
      /**
       * <code>required int64 LoginTimeStamp = 2;</code>
       */
      public Builder setLoginTimeStamp(long value) {
        bitField0_ |= 0x00000002;
        loginTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 LoginTimeStamp = 2;</code>
       */
      public Builder clearLoginTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg_Login_S2C)
    }

    static {
      defaultInstance = new Msg_Login_S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg_Login_S2C)
  }

  public interface Msg_Connect_S2COrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MsgType MsgID = 1 [default = Connect_S2C];
    /**
     * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
     */
    Msg.MsgType getMsgID();
  }
  /**
   * Protobuf type {@code Msg_Connect_S2C}
   */
  public static final class Msg_Connect_S2C extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Connect_S2COrBuilder {
    // Use Msg_Connect_S2C.newBuilder() to construct.
    private Msg_Connect_S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_Connect_S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_Connect_S2C defaultInstance;
    public static Msg_Connect_S2C getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_Connect_S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_Connect_S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Msg.MsgType value = Msg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_Msg_Connect_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_Msg_Connect_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.Msg_Connect_S2C.class, Msg.Msg_Connect_S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_Connect_S2C> PARSER =
        new com.google.protobuf.AbstractParser<Msg_Connect_S2C>() {
      public Msg_Connect_S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_Connect_S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_Connect_S2C> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MsgType MsgID = 1 [default = Connect_S2C];
    public static final int MSGID_FIELD_NUMBER = 1;
    private Msg.MsgType msgID_;
    /**
     * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
     */
    public Msg.MsgType getMsgID() {
      return msgID_;
    }

    private void initFields() {
      msgID_ = Msg.MsgType.Connect_S2C;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.Msg_Connect_S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Connect_S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Connect_S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Msg_Connect_S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Msg_Connect_S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Connect_S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Connect_S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.Msg_Connect_S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.Msg_Connect_S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Msg_Connect_S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.Msg_Connect_S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg_Connect_S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.Msg_Connect_S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_Msg_Connect_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_Msg_Connect_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.Msg_Connect_S2C.class, Msg.Msg_Connect_S2C.Builder.class);
      }

      // Construct using Msg.Msg_Connect_S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = Msg.MsgType.Connect_S2C;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_Msg_Connect_S2C_descriptor;
      }

      public Msg.Msg_Connect_S2C getDefaultInstanceForType() {
        return Msg.Msg_Connect_S2C.getDefaultInstance();
      }

      public Msg.Msg_Connect_S2C build() {
        Msg.Msg_Connect_S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.Msg_Connect_S2C buildPartial() {
        Msg.Msg_Connect_S2C result = new Msg.Msg_Connect_S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.Msg_Connect_S2C) {
          return mergeFrom((Msg.Msg_Connect_S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.Msg_Connect_S2C other) {
        if (other == Msg.Msg_Connect_S2C.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.Msg_Connect_S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.Msg_Connect_S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MsgType MsgID = 1 [default = Connect_S2C];
      private Msg.MsgType msgID_ = Msg.MsgType.Connect_S2C;
      /**
       * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
       */
      public Msg.MsgType getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
       */
      public Builder setMsgID(Msg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MsgType MsgID = 1 [default = Connect_S2C];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = Msg.MsgType.Connect_S2C;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg_Connect_S2C)
    }

    static {
      defaultInstance = new Msg_Connect_S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg_Connect_S2C)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Login_C2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Login_C2S_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Login_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Login_S2C_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Connect_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Connect_S2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\"j\n\rMsg_Login_C2S\022\"\n\005MsgID\030\001 " +
      "\001(\0162\010.MsgType:\tLOGIN_C2S\022\021\n\tconMethod\030\002 " +
      "\002(\005\022\016\n\006szName\030\003 \002(\t\022\022\n\nszPassWord\030\004 \002(\t\"" +
      "K\n\rMsg_Login_S2C\022\"\n\005MsgID\030\001 \001(\0162\010.MsgTyp" +
      "e:\tLOGIN_S2C\022\026\n\016LoginTimeStamp\030\002 \002(\003\"7\n\017" +
      "Msg_Connect_S2C\022$\n\005MsgID\030\001 \001(\0162\010.MsgType" +
      ":\013Connect_S2C*F\n\007MsgType\022\r\n\tLOGIN_C2S\020\000\022" +
      "\r\n\tLOGIN_S2C\020\001\022\017\n\013Connect_S2C\020\002\022\014\n\010Chat_" +
      "C2S\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Msg_Login_C2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Msg_Login_C2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Login_C2S_descriptor,
              new java.lang.String[] { "MsgID", "ConMethod", "SzName", "SzPassWord", });
          internal_static_Msg_Login_S2C_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Msg_Login_S2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Login_S2C_descriptor,
              new java.lang.String[] { "MsgID", "LoginTimeStamp", });
          internal_static_Msg_Connect_S2C_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Msg_Connect_S2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Connect_S2C_descriptor,
              new java.lang.String[] { "MsgID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
