//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocols/MsgChat.proto
namespace MsgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Chat_C2S")]
  public partial class Msg_Chat_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Chat_C2S() {}
    
    private int _MsgID = (int)3;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)3)]
    public int MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private MsgPB.CHANNEL _channel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MsgPB.CHANNEL channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private int _receiver = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"receiver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int receiver
    {
      get { return _receiver; }
      set { _receiver = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CHANNEL")]
    public enum CHANNEL
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORLD", Value=1)]
      WORLD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM", Value=2)]
      ROOM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND", Value=3)]
      FRIEND = 3
    }
  
}